version: "3.8"
services:
  notebooks:
    build: notebooks
    ports:
      - 8888:8888
    volumes:
      - type: bind
        source: ./notebooks/notebooks
        target: /home/jovyan/notebooks
      - type: bind
        source: ./data
        target: /home/jovyan/data
      - type: bind
        source: ./search/data
        target: /home/jovyan/data/search
    env_file:
      - .env
    environment:
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:latest
    volumes:
      - type: bind
        source: ./data/neo4j/data
        target: /data
      - type: bind
        source: ./data/neo4j/logs
        target: /logs
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    env_file: .env
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*

  search:
    build: search
    volumes:
      - type: bind
        source: ./search
        target: /app
    ports:
      - 3000:3000
    command: yarn dev

  graph:
    build: pipeline
    working_dir: /app
    env_file: .env
    depends_on:
      - neo4j
    volumes:
      - type: bind
        source: ./data/stories
        target: /data/
    command: python graph.py
  reindex:
    build: pipeline
    working_dir: /app
    env_file: .env
    depends_on:
      - neo4j
    volumes:
      - type: bind
        source: ./data/elastic
        target: /data/elastic
    command: python reindex.py
  neighbours:
    build: pipeline
    working_dir: /app
    env_file: .env
    depends_on:
      - neo4j
    command: python neighbours.py
  pipeline:
    build: pipeline
    working_dir: /app
    env_file: .env
    depends_on:
      - neo4j
    volumes:
      - type: bind
        source: ./data/
        target: /data/
    command: > 
      sh -c "python graph.py &&
             python reindex.py &&
             python neighbours.py"
