version: "3.8"
services:
  notebooks:
    build: notebooks
    ports:
      - 8888:8888
    volumes:
      - type: bind
        source: ./notebooks/notebooks
        target: /home/jovyan/notebooks
      - type: bind
        source: ./data
        target: /home/jovyan/data
      - type: bind
        source: ./search/data
        target: /home/jovyan/data/search
      - type: bind
        source: ./pipeline/src
        target: /home/jovyan/src
    env_file:
      - .env
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - CACHE_DIRECTORY=/home/jovyan/data/cache

  neo4j:
    image: neo4j:4.4.3
    volumes:
      - type: bind
        source: ./data/neo4j/data
        target: /data
      - type: bind
        source: ./data/neo4j/logs
        target: /logs
      - type: bind
        source: ./data/neo4j/dump
        target: /dump
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    env_file: .env
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*

  search:
    build: search
    volumes:
      - type: bind
        source: ./search
        target: /app
    ports:
      - 3000:3000
    command: yarn dev

  graph:
    build: pipeline
    env_file: .env
    volumes:
      - type: bind
        source: ./data
        target: /data
    command: python graph.py

  neighbours:
    build: pipeline
    env_file: .env
    volumes:
      - type: bind
        source: ./data
        target: /data
    command: python neighbours.py

  reindex:
    build: pipeline
    env_file: .env
    volumes:
      - type: bind
        source: ./search/data
        target: /data
      - type: bind
        source: ./data/cache
        target: /data/cache
    command: python reindex.py

  pipeline:
    build: pipeline
    env_file: .env
    volumes:
      - type: bind
        source: ./data
        target: /data
    command: >
      sh -c "python graph.py && python neighbours.py && python reindex.py"
