version: "3.8"
services:
  graph_store:
    build: graph_store/
    volumes:
      - ${HOME}/.aws/credentials:/root/.aws/credentials:ro
    command: python graph_store.py populate
    depends_on:
      - enricher
  enricher:
    build: enricher/
    ports:
      - 80:80
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
  graph_query_api:
    build: graph_query_api/
    volumes:
      - ${HOME}/.aws/credentials:/root/.aws/credentials:ro
    ports:
      - 80:80
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
  notebooks:
    build: notebooks
    ports:
      - 8888:8888
    volumes:
      - type: bind
        source: ./notebooks/notebooks
        target: /home/jovyan/notebooks
      - type: bind
        source: ./data/common
        target: /home/jovyan/data
      - type: bind
        source: ./stories/search/data
        target: /home/jovyan/data/stories/search
    env_file:
      - .env
    environment:
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:latest
    volumes:
      - type: bind
        source: ./data/neo4j/data
        target: /data
      - type: bind
        source: ./data/neo4j/logs
        target: /logs
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    env_file: .env
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
  stories_pipeline:
    build: stories/pipeline/
    env_file: .env
    depends_on:
      - neo4j
    volumes:
      - type: bind
        source: ./data/common/stories
        target: /data
