version: "3.8"
services:
  graph_store:
    build: graph_store/
    volumes:
      - ${HOME}/.aws/credentials:/root/.aws/credentials:ro
    command: python graph_store.py populate
    depends_on:
      - enricher
  enricher:
    build: enricher/
    ports:
      - 80:80
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
  graph_query_api:
    build: graph_query_api/
    volumes:
      - ${HOME}/.aws/credentials:/root/.aws/credentials:ro
    ports:
      - 80:80
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
  notebooks:
    build: notebooks
    ports:
      - 8888:8888
    volumes:
      - type: bind
        source: ./notebooks/notebooks
        target: /home/jovyan/notebooks
      - type: bind
        source: ./data/common
        target: /home/jovyan/data
    env_file:
      - .env
    environment:
      - JUPYTER_ENABLE_LAB=yes
